[phases.setup]
nixPkgs = ['dotnet-sdk_8']

[phases.build]
cmds = [
    'cd CustomsBot',
    'dotnet restore',
    'dotnet publish -c Release -o /app/out'
]

[start]
cmd = 'dotnet /app/out/CustomsBot.dll'
