[phases.setup]
nixPkgs = ['dotnet-sdk_8']

[phases.build]
cmds = [
    'dotnet restore CustomsBot/CustomsBot.csproj',
    'dotnet publish CustomsBot/CustomsBot.csproj -c Release -o out'
]

[start]
cmd = 'dotnet out/CustomsBot.dll'
